# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0002_auto_20160422_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionmanagement',
            name='creater',
        ),
    ]
